[workspace]
resolver = "2"
members = [
  "noodlez",
  "benchmarks"
]

[workspace.dependencies]
noodlez = { path = "./noodlez" }

criterion = { version = "0.5.1", feature = ["html-reports"] }
indexmap = "2.2.5"
miette = { version = "7.2.0", features = ["fancy"] }
petgraph = "0.6.4"
slotmap = "1.0.7"
thiserror = "1.0.58"
