[package]
name = "noodlez"
version = "0.1.0"
edition = "2021"

[dependencies]
winnow = "0.6.5"

[dev-dependencies]
slotmap = "1.0.7"
indexmap = "2.2.5"
petgraph = "0.6.4"
criterion = { version = "0.5.1", feature = ["html-reports"] }

[[bench]]
name = "slotmap_vs_indexmap"
harness = false

[[bench]]
name = "petgraph_baseline"
harness = false
